# fly.toml app configuration file generated for aral-prices on 2023-09-16T17:03:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aral-prices"
primary_region = "ams"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
